// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Uuid      pgtype.UUID
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
}
