// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, email, first_name, last_name FROM users
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetUserByUUID(ctx context.Context, uuid pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}
